# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Projetos
    url: 'project'
    weight: 20
    
  - name: Palestras e Cursos
    identifier: cursos
    weight: 30
  - name: Introdução a R
    url: /cursos/intro-r
    parent: cursos
    weight: 10
  - name: Produção de Mapas no Qgis
    parent: cursos
    url: cursos/fazer-mapas-qgis
    weight: 20
  - name: Produção de Mapas no R
    parent: cursos
    url: cursos/fazer-mapas-r
    weight: 30
  - name: Distribuição de Espécies
    parent: cursos
    url: cursos/species-model
    weight: 40

  - name: Disciplinas
    identifier: aulas
    weight: 40
  - name: Operações Unitárias
    parent: aulas
    url: aulas/operacoes
    weight: 10
  - name: Epidemiologia (Biomed)
    parent: aulas
    url: aulas/epidemio-biomed
    weight: 20
  - name: Est. e Fun. Educação
    parent: aulas
    url: aulas/est-fun-educação
    weight: 30
  - name: Epidemiologia (Farm)
    parent: aulas
    url: aulas/epidemio-farm
    weight: 40
  - name: Matemática (Biomed e Biolog)
    parent: aulas
    url: aulas/academic/
    weight: 50
  - name: Genética de Populações
    parent: aulas
    url: aulas/academic/
    weight: 60
  - name: Zoologia Amniotas
    parent: aulas
    url: aulas/academic/
    weight: 70

  - name: Blog
    url: 'post'
    weight: 50
  - name: Publicações
    url: 'publicacoes/'
    weight: 60
  - name: Contacto
    url: '#contact'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
