# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Projetos
    url: 'project'
    weight: 30
  - name: Palestras e Cursos
    url: 'cursos'
    weight: 40

  - name: Disciplinas
    identifier: aulas
    weight: 40
  - name: Operações Unitárias
    parent: aulas
    url: aulas/academic/
    weight: 20
  - name: Epidemiologia (Biomed)
    parent: aulas
    url: aulas/academic/
    weight: 20
  - name: Est. e Fun. Educação
    parent: aulas
    url: aulas/academic/
    weight: 20
  - name: Epidemiologia (Farm)
    parent: aulas
    url: aulas/academic/
    weight: 20

    weight: 40
  - name: Blog
    url: 'post'
    weight: 40
  - name: Publicações
    url: 'publicacoes/'
    weight: 50
  - name: Contacto
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
